import type { Metadata } from 'next';
import { Source_Sans_3 } from 'next/font/google';
import './globals.css';
import Header from '@/components/common/header';
import Footer from '@/components/common/footer';
import { ClerkProvider } from '@clerk/nextjs';
import { Toaster } from '@/components/ui/sonner';
const fontSans = Source_Sans_3({
  variable: '--font-sans',
  subsets: ['latin'],
  weight: ['200', '300'],
});

export const metadata: Metadata = {
  title: 'Next Project',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${fontSans.variable}`}>
          <div className="flex flex-col min-h-screen">
            <Header />
            <Toaster />
            <main className="grow">{children}</main>

            <Footer />
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
